---
title: "[develop] 탈퇴 회원 로그인 방지 로직 추가 중 에러 조건을 제대로 타지 않는 문제"
excerpt: "."

writer: Audrey
categories: [develop]

toc: true
toc_sticky: true

pin: true

date: 2025-04-29 11:40:00 +09:00
last_modified_at: 2025-04-29 11:40:00 +09:00

tags: [develop]
---

회원 탈퇴 기능을 구현하면서, 로그인에서도 탈퇴 회원이면 막는 로직을 새롭게 추가해야 했다.

```java
@Override
public UserDetails loadUserByUsername(String id) throws UsernameNotFoundException {

    MemberEntity member = memberRepository.findById(id)
            .orElseThrow(() -> new UsernameNotFoundException("사용자를 찾을 수 없습니다: " + id));

    if(member.isState()) {
        throw new DisabledException("탈퇴한 회원입니다.");
    }

    return new CustomUserDetails(member);
}
```

- 위와 같이 member의 state값이 true일 경우, 탈퇴한 회원이므로 DisabledException을 던지고, 탈퇴한 회원이라는 메시지를 전달한다.

<br>

```java
private String getExceptionMessage(AuthenticationException exception) {

	if(cause instanceof BadCredentialsException) {
	    return "아이디 혹은 비밀번호를 다시 확인해주세요.";
	} else if(cause instanceof DisabledException){
	    return "탈퇴한 회원입니다.";
	} else {
	    return "알 수 없는 에러입니다.";
	}
}
```

- 위의 CustomUserDetailsService에서 던진 에러를 LoginFailureHandler에서 받아서 exception의 타입에 따라 다른 메시지를 프론트로 전달하려고… 했으나 무조건 알수 없는 에러입니다. 라고만 뜬다.
- 근데 비밀번호가 다른 경우에는 정상적으로 아이디 혹은 비밀번호를 다시 확인해주세요. 라고 뜬다.

<br>

알고보니, loadUserByUsername안에서 발생하는 예외인 DisabledException은 InternalAuthenticationServiceException으로 한번 더 감싸져 있었다.

```java
protected final UserDetails retrieveUser(String username, UsernamePasswordAuthenticationToken authentication) throws AuthenticationException {
    this.prepareTimingAttackProtection();

    try {
        UserDetails loadedUser = this.getUserDetailsService().loadUserByUsername(username);
        if (loadedUser == null) {
            throw new InternalAuthenticationServiceException("UserDetailsService returned null, which is an interface contract violation");
        } else {
            return loadedUser;
        }
    } catch (UsernameNotFoundException ex) {
        this.mitigateAgainstTimingAttack(authentication);
        throw ex;
    } catch (InternalAuthenticationServiceException ex) {
        throw ex;
    } catch (Exception ex) { // DisabledException은 이곳으로
        throw new InternalAuthenticationServiceException(ex.getMessage(), ex);
    }
}
```

- 그래서 exception instanceof DisabledException이 false가 나오는 것이었다.

<br>

그래서 아래와 같이 exception.getCause값의 null 여부에 따라 예외를 꺼내놓고 해당 예외를 가지고 타입을 비교해야 한다.

```java
Throwable cause = (exception.getCause() != null) ? exception.getCause() : exception;

if(cause instanceof BadCredentialsException) {
    return "아이디 혹은 비밀번호를 다시 확인해주세요.";
} else if(cause instanceof DisabledException){
    return "탈퇴한 회원입니다.";
} else {
    return "알 수 없는 에러입니다.";
}
```