---
title: "[develop] 리뷰 작성 테스트 중 에러 발생했으나 롤백되지 않는 문제"
excerpt: "."

writer: Audrey
categories: [develop]

toc: true
toc_sticky: true

pin: true

date: 2025-05-01 23:57:00 +09:00
last_modified_at: 2025-05-01 23:57:00 +09:00
tags: [develop]
---

마이페이지까지 구현한 후 최종 테스트 체크 리스트를 작성한 후 리뷰 작성 부분을 테스트 하고 있었다.

새 제품 추가를 해서 리뷰를 작성하고 리뷰 이미지를 선택한 뒤 리뷰 저장을 눌렀는데..

- 저장된 리뷰를 보니 이미지가 저장이 안되어 있었다.
- 이미지 업로드가 안되었나? 하고 테이블을 보니까 아예 review_image_t에 리뷰 이미지 데이터가 저장이 안되어 있었다. + 이미지 업로드도 안되어 있었다.
- 내 의도대로라면 이미지 업로드를 할 때 DB에 먼저 저장을 한 후 실제 경로에 이미지를 업로드하는데, DB에 저장이 안된다면 업로드 하기 전에 롤백이 되어야 한다.
    - 근데 지금 DB에 데이터가 저장되지 않는 문제가 발생했으나 롤백이 안된 것이다.  

<br>

코드를 다시 살펴보고, 리뷰 작성 메소드인 insertReview에서 호출하는 insertReviewImage 메소드 코드를 살펴 보았다.
```java
// 리뷰 이미지 저장
@Override
public void insertReviewImage(MultipartFile[] files, ReviewEntity review, int representIndex) throws IOException {

    if(files == null || files.length == 0 || files[0].isEmpty()) {
        return;
    }
    List<String> imageUrlList = myFileUtils.getImageUrlList(files, "review");
    for(int i = 0; i < imageUrlList.size(); i++) {

        ReviewImageEntity reviewImage = ReviewImageEntity.builder()
                .reviewEntity(review)
                .reviewImagePath(imageUrlList.get(i))
                .build();

        reviewImage.setRepresent(i == representIndex);
        reviewImageRepository.save(reviewImage);
    }

    myFileUtils.uploadImage(files, imageUrlList, "review");
}
```

- 여기서 에러가 생기면 IOException을 던진다.

<br>

찾아보니 @Transactional은 기본적으로 Checked Exception을 Rollback시키지 않는다.  
- IOException, ClassNotFoundException 등은 Checked Exception이다.  
- insertReview 메소드 안에서 IOException이 발생해서 이걸 상위 메소드로 던지면 Spring에서는 이걸 롤백 대상으로 보지 않기 때문에 DB가 저장된것이 취소되지 않았던 것이다.

<br>

그래서 아래와 같이 RuntimeException을 상속받는 CustomException을 일부러 던져보았다.

```java
// 강제 예외 발생..
if (true) {
    throw new CustomException(ErrorCode.FILE_UPLOAD_FAIL,
            ErrorCode.FILE_UPLOAD_FAIL.formatMessage("리뷰 테스트"));
}
```

- 그러자 try-catch 문 안에서 발생한 위의 에러를 잡아서 에러를 던져주고, 클라이언트에 올바른 메시지가 전달되었다. 물론 앞에서 저장된 리뷰 데이터도 모두 롤백 되었다.

<br>

```java
@Override
public void insertReviewImage(MultipartFile[] files, ReviewEntity review, int representIndex) {

    if(files == null || files.length == 0 || files[0].isEmpty()) {
        return;
    }

    try {
        List<String> imageUrlList = myFileUtils.getImageUrlList(files, "review");
        for(int i = 0; i < imageUrlList.size(); i++) {

            ReviewImageEntity reviewImage = ReviewImageEntity.builder()
                    .reviewEntity(review)
                    .reviewImagePath(imageUrlList.get(i))
                    .build();

            reviewImage.setRepresent(i == representIndex);
            reviewImageRepository.save(reviewImage);
        }
        myFileUtils.uploadImage(files, imageUrlList, "review");

    } catch (Exception e) {
        throw new CustomException(ErrorCode.FILE_UPLOAD_FAIL,
                ErrorCode.FILE_UPLOAD_FAIL.formatMessage("리뷰"));
    }
}
```

- 위와 같이 에러 처리 로직을 변경하였다.
- 기존에는 myFileUtils.uploadImage에서 IOException을 던지면 그것을 받아서 또 상위 메소드인 insertReview에 던지고, insertReview에서 그 에러를 처리하는 것으로 했었다.
    - 이제는 myFileUtils에서 IOException을 던지면 insertReviewImage에서 catch문에서 이 에러를 잡아서 처리한다.
    - 이때 던지는 CustomException은 RuntimeException을 상속 받기 때문에 예외가 발생하면 자동 RollBack된다.

<br>

```java
@Override
@Transactional
public Map<String, Object> insertReview(ReviewRequestDTO reviewRequestDTO, MultipartFile[] files, CustomUserDetails user) {

    ProductEntity product = handleProduct(reviewRequestDTO);
    ReviewEntity review = insertReviewFields(reviewRequestDTO, product, user);
    int representIndex = reviewRequestDTO.getRepresentIndex();

    updateProductStats(product, review, new ReviewDTO(), UpdateAction.INSERT);
    insertReviewImage(files, review, representIndex);

    return Map.of("success", true
            , "message", "리뷰가 작성되었습니다."
            , "redirectUrl", "/product/productDetail.page?productId=" + product.getProductId());
}
```

- 이제 이미지 업로드 관련 에러는 insertReviewImage에서 처리하므로 최상위 메소드인 insertReview의 코드가 더 깔끔해졌다.